server:
  port: 8090
  servlet:
    context-path: /youareright
  tomcat:
    uri-encoding: utf-8
    connection-timeout: 60000
    
spring:
  main: 
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanghuan?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: hzc990712
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
  servlet:
    multipart:
      enabled: true      max-file-size: 5MB
      max-request-size: 100MB
              

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.youareright.model
  

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.wanghuan: DEBUG
    


  